%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/melodic/.*$
%global __requires_exclude_from ^/opt/ros/melodic/.*$

Name:           ros-melodic-robot-calibration
Version:        0.6.1
Release:        1%{?dist}
Summary:        ROS robot_calibration package

License:        Apache2
URL:            http://ros.org/wiki/robot_calibration
Source0:        %{name}-%{version}.tar.gz

Requires:       ceres-solver-devel
Requires:       protobuf-compiler
Requires:       protobuf-devel
Requires:       ros-melodic-actionlib
Requires:       ros-melodic-camera-calibration-parsers
Requires:       ros-melodic-control-msgs
Requires:       ros-melodic-cv-bridge
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-kdl-parser
Requires:       ros-melodic-moveit-msgs
Requires:       ros-melodic-nav-msgs
Requires:       ros-melodic-orocos-kdl
Requires:       ros-melodic-pluginlib
Requires:       ros-melodic-robot-calibration-msgs
Requires:       ros-melodic-rosbag
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-tf
Requires:       ros-melodic-tf2-geometry-msgs
Requires:       ros-melodic-tf2-ros
Requires:       ros-melodic-visualization-msgs
Requires:       suitesparse-devel
BuildRequires:  ceres-solver-devel
BuildRequires:  gflags-devel
BuildRequires:  protobuf-compiler
BuildRequires:  protobuf-devel
BuildRequires:  ros-melodic-actionlib
BuildRequires:  ros-melodic-camera-calibration-parsers
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-code-coverage
BuildRequires:  ros-melodic-control-msgs
BuildRequires:  ros-melodic-cv-bridge
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-kdl-parser
BuildRequires:  ros-melodic-moveit-msgs
BuildRequires:  ros-melodic-nav-msgs
BuildRequires:  ros-melodic-orocos-kdl
BuildRequires:  ros-melodic-pluginlib
BuildRequires:  ros-melodic-robot-calibration-msgs
BuildRequires:  ros-melodic-rosbag
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-tf
BuildRequires:  ros-melodic-tf2-geometry-msgs
BuildRequires:  ros-melodic-tf2-ros
BuildRequires:  ros-melodic-visualization-msgs
BuildRequires:  suitesparse-devel

%description
Calibrate a Robot

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/melodic

%changelog
* Tue Nov 19 2019 Michael Ferguson <mike@vanadiumlabs.com> - 0.6.1-1
- Autogenerated by Bloom

* Mon Jul 09 2018 Michael Ferguson <mike@vanadiumlabs.com> - 0.6.0-0
- Autogenerated by Bloom

